# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autosign.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

file = open('.\\name.cfg', 'r')
NAMELIST = []
for line in file.readlines():
    line = line.rstrip().split(' ')
    if line[0]:
        NAMELIST.append(line[0])
file.close()
SIZE=len(NAMELIST)

class Ui_Autosign(object):
    def setupUi(self, Autosign):
        Autosign.setObjectName("Autosign")
        Autosign.resize(443, 273)
        Autosign.setToolTipDuration(7)
        self.widget = QtWidgets.QWidget(Autosign)
        self.widget.setGeometry(QtCore.QRect(11, 11, 420, 249))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.XlineEdit = QtWidgets.QLineEdit(self.widget)
        self.XlineEdit.setEnabled(True)
        self.XlineEdit.setObjectName("XlineEdit")
        self.horizontalLayout_3.addWidget(self.XlineEdit)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.YlineEdit = QtWidgets.QLineEdit(self.widget)
        self.YlineEdit.setObjectName("YlineEdit")
        self.horizontalLayout_3.addWidget(self.YlineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox1 = QtWidgets.QCheckBox(self.widget)
        self.checkBox1.setChecked(True)
        self.checkBox1.setObjectName("checkBox1")
        self.horizontalLayout_7.addWidget(self.checkBox1)
        self.checkBox2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox2.setChecked(True)
        self.checkBox2.setObjectName("checkBox2")
        self.horizontalLayout_7.addWidget(self.checkBox2)
        self.checkBox3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox3.setObjectName("checkBox3")
        self.horizontalLayout_7.addWidget(self.checkBox3)
        self.checkBox4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox4.setChecked(True)
        self.checkBox4.setObjectName("checkBox4")
        self.horizontalLayout_7.addWidget(self.checkBox4)
        self.checkBox5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox5.setChecked(True)
        self.checkBox5.setObjectName("checkBox5")
        self.horizontalLayout_7.addWidget(self.checkBox5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.AddresslineEdit = QtWidgets.QLineEdit(self.widget)
        self.AddresslineEdit.setObjectName("AddresslineEdit")
        self.verticalLayout_2.addWidget(self.AddresslineEdit)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        for i in range(SIZE):
            self.comboBox.addItem("")

        self.horizontalLayout_8.addWidget(self.comboBox)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.datelineEdit_1 = QtWidgets.QLineEdit(self.widget)
        self.datelineEdit_1.setEnabled(True)
        self.datelineEdit_1.setText("")
        self.datelineEdit_1.setObjectName("datelineEdit_1")
        self.horizontalLayout_8.addWidget(self.datelineEdit_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        for i in range(SIZE):
            self.comboBox_2.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.datelineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.datelineEdit_2.setEnabled(True)
        self.datelineEdit_2.setText("")
        self.datelineEdit_2.setObjectName("datelineEdit_2")
        self.horizontalLayout_6.addWidget(self.datelineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setObjectName("comboBox_3")
        for i in range(SIZE):
            self.comboBox_3.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_3)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.datelineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.datelineEdit_3.setEnabled(True)
        self.datelineEdit_3.setText("")
        self.datelineEdit_3.setObjectName("datelineEdit_3")
        self.horizontalLayout_5.addWidget(self.datelineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget)
        self.comboBox_4.setObjectName("comboBox_4")
        for i in range(SIZE):
            self.comboBox_4.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_4)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.datelineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.datelineEdit_4.setEnabled(True)
        self.datelineEdit_4.setText("")
        self.datelineEdit_4.setObjectName("datelineEdit_4")
        self.horizontalLayout_4.addWidget(self.datelineEdit_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget)
        self.comboBox_5.setObjectName("comboBox_5")
        for i in range(SIZE):
            self.comboBox_5.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_5)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.datelineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.datelineEdit_5.setEnabled(True)
        self.datelineEdit_5.setText("")
        self.datelineEdit_5.setObjectName("datelineEdit_5")
        self.horizontalLayout_2.addWidget(self.datelineEdit_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox2_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox2_2.setObjectName("checkBox2_2")
        self.horizontalLayout.addWidget(self.checkBox2_2)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.AtypelineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.AtypelineEdit_2.setEnabled(True)
        self.AtypelineEdit_2.setText("")
        self.AtypelineEdit_2.setObjectName("AtypelineEdit_2")
        self.horizontalLayout.addWidget(self.AtypelineEdit_2)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.AtypelineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.AtypelineEdit_3.setEnabled(True)
        self.AtypelineEdit_3.setText("400,300")
        self.AtypelineEdit_3.setObjectName("AtypelineEdit_3")
        self.horizontalLayout.addWidget(self.AtypelineEdit_3)
        self.signButton = QtWidgets.QPushButton(self.widget)
        self.signButton.setObjectName("signButton")
        self.horizontalLayout.addWidget(self.signButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Autosign)
        QtCore.QMetaObject.connectSlotsByName(Autosign)

    def retranslateUi(self, Autosign):
        _translate = QtCore.QCoreApplication.translate
        Autosign.setWindowTitle(_translate("Autosign", "Autosign"))
        self.label.setText(_translate("Autosign", "X-direction"))
        self.XlineEdit.setText(_translate("Autosign", "0,0"))
        self.label_2.setText(_translate("Autosign", "Y-direction"))
        self.YlineEdit.setText(_translate("Autosign", "0,0"))
        self.checkBox1.setText(_translate("Autosign", "Design"))
        self.checkBox2.setText(_translate("Autosign", "Check"))
        self.checkBox3.setText(_translate("Autosign", "Verify1"))
        self.checkBox4.setText(_translate("Autosign", "Verify2"))
        self.checkBox5.setText(_translate("Autosign", "Approve"))
        self.label_3.setText(_translate("Autosign", "Address"))
        self.label_4.setText(_translate("Autosign", "Design"))
        self.label_5.setText(_translate("Autosign", "Check"))
        self.label_6.setText(_translate("Autosign", "Verify1"))
        self.label_7.setText(_translate("Autosign", "Verify2"))
        self.label_8.setText(_translate("Autosign", "Approve"))
        self.label_9.setText(_translate("Autosign", "Date"))
        self.label_10.setText(_translate("Autosign", "Date"))
        self.label_11.setText(_translate("Autosign", "Date"))
        self.label_12.setText(_translate("Autosign", "Date"))
        self.label_13.setText(_translate("Autosign", "Date"))
        self.AddresslineEdit.setText(_translate("Autosign", "D:\\autosign"))

        comboboxlist=[self.comboBox,self.comboBox_2,self.comboBox_3,self.comboBox_4,self.comboBox_5]
        for i in range(SIZE):
            for combo in comboboxlist:
                combo.setItemText(i, _translate("Autosign", NAMELIST[i]))

        self.checkBox2_2.setText(_translate("Autosign", "A-type"))
        self.label_14.setText(_translate("Autosign", "Date"))
        self.label_15.setText(_translate("Autosign", "Height"))
        self.signButton.setText(_translate("Autosign", "Autosign"))
